import html
import json
import re
from pathlib import Path

import markdown
import yaml
from fastapi import APIRouter, Form, HTTPException, Request
from fastapi.responses import HTMLResponse, RedirectResponse

from src.query import confidence_label
from src.utils import append_domain_log, append_line, atomic_write, now_iso
from src.validate import parse_frontmatter
from src.web.routes.shared import list_domains

router = APIRouter()

MD_EXTENSIONS = ["tables", "fenced_code", "sane_lists", "nl2br"]
WIKILINK_RE = re.compile(r"\[\[([^\]|]+?)(?:\|([^\]]+?))?\]\]")


@router.get("/wiki/{domain}", response_class=HTMLResponse)
async def wiki_browse(request: Request, domain: str):
    repo_root: Path = request.app.state.repo_root
    templates = request.app.state.templates
    domain_dir = repo_root / "domains" / domain

    pages = []
    by_type: dict[str, list[dict]] = {}
    all_tags: set[str] = set()
    if domain_dir.exists():
        for md_file in sorted(domain_dir.rglob("*.md")):
            if "indexes" in md_file.parts or ".archive" in md_file.parts:
                continue
            if md_file.name in ("index.md", "log.md", "schema.md"):
                continue
            fm, _ = parse_frontmatter(md_file)
            if not fm.get("title"):
                continue
            conf = float(fm.get("confidence", 0.0) or 0.0)
            tags = [str(t) for t in (fm.get("tags") or [])]
            all_tags.update(tags)
            entry = {
                "title": fm["title"],
                "rel_path": str(md_file.relative_to(repo_root)),
                "type": fm.get("type", ""),
                "status": fm.get("status", ""),
                "confidence": conf,
                "confidence_label": confidence_label(conf),
                "tags": tags,
                "created_at": str(fm.get("created_at", "") or ""),
                "updated_at": str(fm.get("updated_at", "") or ""),
            }
            pages.append(entry)
            by_type.setdefault(entry["type"] or "other", []).append(entry)

    connections = _load_connections(domain_dir)

    title_to_page = {_norm_title(p["title"]): p for p in pages}
    wiki_root = _render_wiki_root(domain_dir, domain, title_to_page)
    orphans = _find_orphans(pages, connections)

    return templates.TemplateResponse(request, "wiki_browse.html", {
        "domain": domain,
        "pages": pages,
        "by_type": by_type,
        "all_tags": sorted(all_tags),
        "connections": connections,
        "connections_exists": connections is not None,
        "wiki_root_html": wiki_root["html"],
        "wiki_root_exists": wiki_root["exists"],
        "wiki_root_generated_at": wiki_root["generated_at"],
        "orphans": orphans,
    })


def _norm_title(s: str) -> str:
    return " ".join((s or "").strip().lower().split())


def _resolve_wikilinks(body: str, title_to_page: dict, domain: str) -> str:
    """Pre-render pass: rewrite [[Title]] / [[Title|label]] into MD links.

    Markdown has no native wikilink syntax, so we substitute before the
    parser runs. Unresolved targets are kept as plain text in a <span>
    so the reader can see them but isn't given a broken link to click.
    """
    def _sub(m: re.Match) -> str:
        target = m.group(1).strip()
        label = (m.group(2) or target).strip()
        key = _norm_title(target)
        page = title_to_page.get(key)
        if page:
            return f"[{label}](/wiki/{domain}/page/{page['rel_path']})"
        return f'<span class="wikilink-broken" title="No matching page: {html.escape(target)}">{html.escape(label)}</span>'
    return WIKILINK_RE.sub(_sub, body)


def _render_wiki_root(domain_dir: Path, domain: str, title_to_page: dict) -> dict:
    """Render domains/<d>/index.md into HTML with wikilinks resolved."""
    path = domain_dir / "index.md"
    if not path.exists():
        return {"html": "", "exists": False, "generated_at": ""}
    raw = path.read_text(encoding="utf-8")
    body = raw
    generated_at = ""
    m = re.search(r"<!--\s*generated by wikiLLM at ([^\s]+)", raw)
    if m:
        generated_at = m.group(1)
    body = _resolve_wikilinks(body, title_to_page, domain)
    rendered = markdown.markdown(body, extensions=MD_EXTENSIONS)
    return {"html": rendered, "exists": True, "generated_at": generated_at}


def _find_orphans(pages: list[dict], connections: dict | None) -> list[dict]:
    """Pages with zero inbound wikilink edges.

    Falls back to "every page is an orphan" when connections.json hasn't
    been generated yet (wikiGraph never ran). Shared-source and related
    edges are ignored — the definition hinges on *direct calls*, meaning
    an explicit [[wikilink]] pointing at the page.
    """
    if not pages:
        return []
    pages_by_path = {p["rel_path"]: p for p in pages}
    if not connections or not connections.get("edges"):
        return sorted(pages, key=lambda p: (p.get("type", ""), p["title"].lower()))
    inbound: set[str] = set()
    for e in connections["edges"]:
        if e.get("type") != "wikilink":
            continue
        dst = e.get("dst")
        if dst:
            inbound.add(dst)
    orphans = [p for path, p in pages_by_path.items() if path not in inbound]
    return sorted(orphans, key=lambda p: (p.get("type", ""), p["title"].lower()))


def _load_connections(domain_dir: Path) -> dict | None:
    """Return the wikiGraph-generated graph, or None if not yet generated."""
    path = domain_dir / "indexes" / "connections.json"
    if not path.exists():
        return None
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except (json.JSONDecodeError, OSError):
        return None


_METADATA_FILES = {"index.md", "log.md", "schema.md", "domain.yaml"}


def _resolve_page(repo_root: Path, domain: str, rel_path: str) -> Path:
    target = (repo_root / rel_path).resolve()
    base = (repo_root / "domains" / domain).resolve()
    try:
        target.relative_to(base)
    except ValueError:
        raise HTTPException(status_code=400, detail="Invalid page path")
    return target


# NOTE: edit routes must be declared BEFORE wiki_page — its {rel_path:path}
# capture is greedy and would otherwise swallow trailing `/edit`.
@router.get("/wiki/{domain}/page/{rel_path:path}/edit", response_class=HTMLResponse)
async def wiki_edit_form(
    request: Request,
    domain: str,
    rel_path: str,
    error: str = "",
):
    repo_root: Path = request.app.state.repo_root
    templates = request.app.state.templates

    target = _resolve_page(repo_root, domain, rel_path)
    if target.name in _METADATA_FILES:
        raise HTTPException(status_code=400, detail="Refusing to edit domain metadata file")
    if not target.exists() or not target.is_file():
        raise HTTPException(status_code=404, detail="Page not found")

    raw_content = target.read_text(encoding="utf-8")
    fm, _ = parse_frontmatter(target)
    return templates.TemplateResponse(request, "wiki_edit.html", {
        "domain": domain,
        "rel_path": rel_path,
        "raw_content": raw_content,
        "fm": fm,
        "error": error,
    })


@router.post("/wiki/{domain}/page/{rel_path:path}/edit")
async def wiki_edit_save(
    request: Request,
    domain: str,
    rel_path: str,
    raw_content: str = Form(...),
):
    """Overwrite an approved page with edited markdown. Bumps updated_at when
    the frontmatter parses cleanly; otherwise writes the content verbatim."""
    repo_root: Path = request.app.state.repo_root

    target = _resolve_page(repo_root, domain, rel_path)
    if target.name in _METADATA_FILES:
        raise HTTPException(status_code=400, detail="Refusing to edit domain metadata file")
    if not target.exists() or not target.is_file():
        raise HTTPException(status_code=404, detail="Page not found")

    content = raw_content.replace("\r\n", "\n").replace("\r", "\n")
    content = _bump_updated_at(content)

    atomic_write(target, content)

    fm, _ = parse_frontmatter(target)
    title = fm.get("title", target.name)
    append_domain_log(repo_root, domain, "edit", title)
    append_line(
        repo_root / "audit" / "approvals.log",
        f"[{now_iso()}] edit-page | {domain} | {rel_path}",
    )
    return RedirectResponse(f"/wiki/{domain}/page/{rel_path}", status_code=303)


@router.get("/wiki/{domain}/page/{rel_path:path}", response_class=HTMLResponse)
async def wiki_page(request: Request, domain: str, rel_path: str):
    repo_root: Path = request.app.state.repo_root
    templates = request.app.state.templates

    target = _resolve_page(repo_root, domain, rel_path)
    if not target.exists():
        raise HTTPException(status_code=404, detail="Page not found")

    fm, body = parse_frontmatter(target)
    conf = float(fm.get("confidence", 0.0) or 0.0)
    rendered = markdown.markdown(body, extensions=MD_EXTENSIONS)
    return templates.TemplateResponse(request, "wiki_page.html", {
        "domain": domain,
        "fm": fm,
        "body_html": rendered,
        "rel_path": rel_path,
        "confidence": conf,
        "confidence_label": confidence_label(conf),
    })


def _bump_updated_at(content: str) -> str:
    """Re-emit the content with frontmatter `updated_at` set to now. No-op if
    the frontmatter can't be parsed — we still want to save the user's edit."""
    if not content.startswith("---"):
        return content
    parts = content.split("---", 2)
    if len(parts) < 3:
        return content
    try:
        fm = yaml.safe_load(parts[1]) or {}
    except yaml.YAMLError:
        return content
    if not isinstance(fm, dict):
        return content
    fm["updated_at"] = now_iso()
    body = parts[2].lstrip("\n")
    return (
        "---\n"
        + yaml.dump(fm, allow_unicode=True, default_flow_style=False, sort_keys=False)
        + "---\n\n"
        + body
    )


@router.post("/wiki/{domain}/move")
async def wiki_move(
    request: Request,
    domain: str,
    rel_path: str = Form(...),
    target_domain: str = Form(...),
):
    """On-demand move of an approved page to another domain.

    Preserves the subpath under `domains/<domain>/` (e.g. `concepts/foo.md`),
    rewrites the `domain` frontmatter field, and logs the operation.
    """
    repo_root: Path = request.app.state.repo_root

    src = (repo_root / rel_path).resolve()
    src_base = (repo_root / "domains" / domain).resolve()
    try:
        src.relative_to(src_base)
    except ValueError:
        raise HTTPException(status_code=400, detail="Invalid source path")
    if src.name in _METADATA_FILES:
        raise HTTPException(status_code=400, detail="Refusing to move domain metadata file")
    if not src.exists() or not src.is_file():
        raise HTTPException(status_code=404, detail="Page not found")

    known = list_domains(repo_root)
    if target_domain not in known:
        raise HTTPException(status_code=400, detail=f"Unknown target domain: {target_domain}")
    if target_domain == domain:
        raise HTTPException(status_code=400, detail="Target domain must differ from source")

    src_rel = src.relative_to(repo_root)
    parts = list(src_rel.parts)
    parts[1] = target_domain
    new_rel = Path(*parts)
    tgt = (repo_root / new_rel).resolve()
    tgt_base = (repo_root / "domains" / target_domain).resolve()
    try:
        tgt.relative_to(tgt_base)
    except ValueError:
        raise HTTPException(status_code=400, detail="Invalid target path")
    if tgt.exists():
        raise HTTPException(status_code=409, detail=f"Target already exists: {new_rel}")

    fm, body = parse_frontmatter(src)
    fm["domain"] = target_domain
    fm["updated_at"] = now_iso()
    content = (
        "---\n"
        + yaml.dump(fm, allow_unicode=True, default_flow_style=False, sort_keys=False)
        + "---\n\n"
        + body
    )
    atomic_write(tgt, content)
    src.unlink()

    title = fm.get("title", src.name)
    append_domain_log(
        repo_root, domain, "move-out",
        f"{title} → domains/{target_domain}/",
    )
    append_domain_log(
        repo_root, target_domain, "move-in",
        f"{title} ← domains/{domain}/",
    )
    append_line(
        repo_root / "audit" / "approvals.log",
        f"[{now_iso()}] move-page | {rel_path} → {new_rel.as_posix()}",
    )

    return RedirectResponse(
        f"/wiki/{target_domain}/page/{new_rel.as_posix()}",
        status_code=303,
    )


@router.post("/wiki/{domain}/delete")
async def wiki_delete(request: Request, domain: str, rel_path: str = Form(...)):
    """Hard-delete an approved page under domains/<domain>/."""
    repo_root: Path = request.app.state.repo_root
    target = (repo_root / rel_path).resolve()
    base = (repo_root / "domains" / domain).resolve()
    try:
        target.relative_to(base)
    except ValueError:
        raise HTTPException(status_code=400, detail="Invalid page path")
    if target.name in ("index.md", "log.md", "schema.md", "domain.yaml"):
        raise HTTPException(status_code=400, detail="Refusing to delete domain metadata file")
    if not target.exists() or not target.is_file():
        raise HTTPException(status_code=404, detail="Page not found")

    fm, _ = parse_frontmatter(target)
    title = fm.get("title", target.name)
    target.unlink()
    append_domain_log(repo_root, domain, "delete", title)
    append_line(
        repo_root / "audit" / "approvals.log",
        f"[{now_iso()}] delete-page | {domain} | {rel_path}",
    )
    return RedirectResponse(f"/wiki/{domain}", status_code=303)
