import re
from dataclasses import dataclass, field
from datetime import datetime, timezone, date
from pathlib import Path
from src.validate import parse_frontmatter
from src.utils import atomic_write, now_iso


@dataclass
class LintReport:
    domain: str
    low_confidence_pages: list = field(default_factory=list)
    unresolved_contradictions: list = field(default_factory=list)
    orphans: list = field(default_factory=list)
    stale_pages: list = field(default_factory=list)
    stuck_jobs: list = field(default_factory=list)
    index_mismatches: list = field(default_factory=list)


def lint_domain(domain: str, repo_root: Path = Path("."), stale_days: int = 90) -> LintReport:
    report = LintReport(domain=domain)
    domain_dir = repo_root / "domains" / domain
    indexes_dir = domain_dir / "indexes"
    indexes_dir.mkdir(parents=True, exist_ok=True)

    # Collect all approved pages (exclude index files and schema)
    approved_pages = []
    for p in domain_dir.rglob("*.md"):
        if "indexes" not in str(p) and p.name not in ("index.md", "log.md", "schema.md"):
            approved_pages.append(p)

    # Build full content string for orphan detection
    page_texts: dict[Path, str] = {}
    for page in approved_pages:
        page_texts[page] = page.read_text(encoding="utf-8")
    all_content = "\n".join(page_texts.values())

    for page in approved_pages:
        fm, body = parse_frontmatter(page)
        if not fm:
            continue

        confidence = float(fm.get("confidence", 1.0))
        title = fm.get("title", page.name)
        status = fm.get("status", "")
        full_text = page_texts[page]

        # Low confidence check
        if confidence < 0.35 and status == "approved":
            report.low_confidence_pages.append({
                "title": title, "path": str(page), "confidence": confidence
            })

        # Unresolved contradictions check — scan for [!contradiction] blocks with unresolved status
        for block_match in re.finditer(
            r"\[!contradiction\](.*?)(?=\n>\s*\[!|\Z)", full_text, re.DOTALL
        ):
            block = block_match.group(0)
            if re.search(r"status.*unresolved", block, re.IGNORECASE):
                report.unresolved_contradictions.append({
                    "title": title, "path": str(page)
                })
                break

        # Stale pages check
        updated_at = fm.get("updated_at", "")
        if updated_at and status == "approved":
            try:
                ts_str = str(updated_at)
                updated_dt = datetime.fromisoformat(ts_str)
                if updated_dt.tzinfo is None:
                    updated_dt = updated_dt.replace(tzinfo=timezone.utc)
                days_old = (datetime.now(timezone.utc) - updated_dt).days
                if days_old > stale_days:
                    report.stale_pages.append({
                        "title": title, "path": str(page), "days_old": days_old
                    })
            except Exception:
                pass

    # Orphan detection: pages not linked from any other page
    for page in approved_pages:
        fm, _ = parse_frontmatter(page)
        title = fm.get("title", "")
        if not title:
            continue
        page_text = page_texts[page]
        # Build content of all OTHER pages
        other_content = all_content.replace(page_text, "", 1)
        linked = bool(re.search(rf"\[\[{re.escape(title)}\]\]", other_content))
        if not linked:
            report.orphans.append({"title": title, "path": str(page)})

    # Write index files
    _write_low_confidence_index(report, indexes_dir)
    _write_contradictions_index(report, indexes_dir)
    _write_orphans_index(report, indexes_dir)
    _write_stale_index(report, indexes_dir)

    # Append to domain log
    log_path = domain_dir / "log.md"
    if log_path.exists():
        today = date.today().isoformat()
        with open(log_path, "a", encoding="utf-8") as f:
            f.write(
                f"\n## [{today}] lint | "
                f"{len(report.low_confidence_pages)} low-conf, "
                f"{len(report.unresolved_contradictions)} contradictions, "
                f"{len(report.orphans)} orphans\n"
            )

    return report


def _write_low_confidence_index(report: LintReport, indexes_dir: Path) -> None:
    lines = [
        f"# Low Confidence Pages — {report.domain}\n\n"
        "> Auto-generated by lint. Do not edit manually.\n\n"
    ]
    for p in report.low_confidence_pages:
        lines.append(f"- [{p['title']}]({p['path']}) — confidence: {p['confidence']:.2f}\n")
    atomic_write(indexes_dir / "low-confidence.md", "".join(lines))


def _write_contradictions_index(report: LintReport, indexes_dir: Path) -> None:
    lines = [
        f"# Unresolved Contradictions — {report.domain}\n\n"
        "> Auto-generated by lint. Do not edit manually.\n\n"
    ]
    for p in report.unresolved_contradictions:
        lines.append(f"- [{p['title']}]({p['path']})\n")
    atomic_write(indexes_dir / "contradictions.md", "".join(lines))


def _write_orphans_index(report: LintReport, indexes_dir: Path) -> None:
    lines = [
        f"# Orphaned Pages — {report.domain}\n\n"
        "> Auto-generated by lint. Do not edit manually.\n\n"
    ]
    for p in report.orphans:
        lines.append(f"- [{p['title']}]({p['path']})\n")
    atomic_write(indexes_dir / "orphans.md", "".join(lines))


def _write_stale_index(report: LintReport, indexes_dir: Path) -> None:
    lines = [
        f"# Stale Pages — {report.domain}\n\n"
        "> Auto-generated by lint. Do not edit manually.\n\n"
    ]
    for p in report.stale_pages:
        lines.append(f"- [{p['title']}]({p['path']}) — {p['days_old']} days old\n")
    atomic_write(indexes_dir / "stale-pages.md", "".join(lines))
